version: "3.4"

services:
  db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=sousou
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3308:3308'
    volumes:
      - db:/var/lib/mysql
  api:
    build:
      context: .
      target: development
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3399:3399
    links:
      - db
    command: yarn dev-migrate
volumes:
  db:
    driver: local
