version: "3.4"

services:
  db:
    image: mysql:latest
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=sousou
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3308:3306'
    volumes:
      - db:/var/lib/mysql
  api:
    build:
      context: .
      target: production
    ports:
      - 3399:9999
    depends_on:
      - db
    links:
      - db
    # command: yarn migrate
volumes:
  db:
    driver: local
